version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  assignees:
    - "sboulema"
  groups:
    auth0:
      patterns:
        - "Auth0.*"

- package-ecosystem: npm
  directory: "/src"
  schedule:
    interval: daily
  assignees:
    - "sboulema"
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "sboulema"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "sboulema"