name: BabyTracker

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  version: '1.0.${{ github.run_number }}'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
          
      - name: Build
        run: dotnet publish -p:ContainerImageName=${{ secrets.DOCKERHUB_USERNAME }}/babytracker -p:ContainerImageName=ghcr.io/${{ github.actor }}/babytracker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/babytracker --all-tags

      - name: Push Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/babytracker --all-tags  
            
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: /home/sboulema/deployDockerContainer BabyTracker babytracker